export const countries = {
    Continent: [],
    Africa: [
        'Algeria',
        'Angola',
        'Benin',
        'Botswana',
        'Burkina',
        'Burundi',
        'Cameroon',
        'Cape Verde',
        'Chad',
        'Comoros',
        'Congo (Democratic Republic of)',
        'Congo',
        'Dijibouti',
        'Egypt',
        'Equatorial Guinea',
        'Eritrea',
        'Ethiopia',
        'Gabon',
        'Gambia',
        'Ghana',
        'Guinea Bissau',
        'Guinea',
        'Ivory Coast',
        'Kenya',
        'Lesotho',
        'Liberia',
        'Madagascar',
        'Malawi',
        'Mauritania',
        'Mauritius',
        'Morocco',
        'Mozambique',
        'Namibia',
        'Nigeria',
        'Rwanda',
        'Sai Tome and Principe',
        'Senegal',
        'Seychelles',
        'Sierra Leone',
        'South Africa',
        'South Sudan',
        'Sudan (North)',
        'Swaziland',
        'Tanzania',
        'Togo',
        'Tunisia',
        'Uganda',
        'Zambia',
    ],
    Asia: [
        'Azerbaijan',
        'Bahrain',
        'Bangladesh',
        'Bhutan',
        'Brunei',
        'Cambodia',
        'Cyprus',
        'East Timor',
        'India',
        'Indonesia',
        'Iraq',
        'Israel',
        'Japan',
        'Jordan',
        'Kazakhstan',
        'Kuwait',
        'Kyrgyzstan',
        'Laos',
        'Lebanon',
        'Malaysia',
        'Maldives',
        'Mongolia',
        'Nepal',
        'Oman',
        'Pakistan',
        'Philippines',
        'Qatar',
        'Saudi Arabia',
        'Singapore',
        'South Korea',
        'Sri Lanka',
        'Taiwan',
        'Tajikistan',
        'Thailand',
        'Turkmenistan',
        'UAE',
        'Uzbekistan',
        'Vietnam',
    ],
    Europe: [
        'Albania',
        'Andorra',
        'Armenia',
        'Austria',
        'Belgium',
        'Bosnia and Herzegovina',
        'Bulgaria',
        'Croatia',
        'Czech Republic',
        'Denmark',
        'Estonia',
        'Finland',
        'France',
        'Georgia',
        'Germany',
        'Greece',
        'Hungary',
        'Iceland',
        'Ireland',
        'Italy',
        'Latvia',
        'Lieischenstein',
        'Lithuania',
        'Luxembourg',
        'Macedonia',
        'Malta',
        'Moldova',
        'Monaco',
        'Montenegro',
        'Netherlands',
        'Norway',
        'Poland',
        'Portugal',
        'Romania',
        'Russia',
        'San Marino',
        'Serbia',
        'Slovakia',
        'Slovenia',
        'Spain',
        'Sweden',
        'Switzerland',
        'Turkey',
        'UK',
        'Ukraine'
    ],
    Oceania: [
        'Australia',
        'Fiji',
        'Kiribati',
        'Marshall Islands',
        'Micronesia',
        'Nauru',
        'New Zealand',
        'Palau',
        'Papua New Guinea',
        'Samoa',
        'Solomon Islands',
        'Tonga',
        'Tuvalu',
        'Vanuatu'
    ],
    America: [
        'Argentina',
        'Bahamas',
        'Barbados',
        'Belize',
        'Bermuda',
        'Bolivia',
        'Brazil',
        'Canada',
        'Chile',
        'Colombia',
        'Costa Rica',
        'Dominica',
        'Dominican Republic',
        'Ecuador',
        'El Salvador',
        'Grenada',
        'Guatemala',
        'Guyana',
        'Honduras',
        'Jamaica',
        'Mexico',
        'Nicaragua',
        'Panama',
        'Paraguay',
        'Peru',
        'St. Kitts and Nevis',
        'St. Lucia',
        'St. Vincent and The Grenadines',
        'Suriname',
        'Trinidad and Tobago',
        'United States',
        'Uruguay',
        'Venezuela'
    ]
};
